config/routes.rb
Rails.application.routes.draw do

  get 'less_active_members/:id/resource/:rid/:slug' => 'less_active_members#resource', as: :less_active_member_resource
  
  resources :less_active_members do
    member do
      get 'edit_next'
    end
    collection do
      get 'list'
      post 'import_names'
    end
  end

  resources :personal_history_stories

  resources :personal_history_stories, path: :fifty_two_stories

  resources :text_messages

  resources :notes

  resources :assignments

  resources :tasks

  resources :contact_infos

  get 'welcome/index'

  resources :users

  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]  

  root 'welcome#index'
  
  get 'home/' => 'home#index'

  resources :recipes, only: [:index, :show, :create, :update, :destroy]
end

app/models/contact_info.rb
class ContactInfo < ActiveRecord::Base
  audited
  belongs_to :user
end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
  before_action :set_contact_info, only: [:show, :edit, :update, :destroy]

  # GET /contact_infos
  # GET /contact_infos.json
  def index
    @contact_infos = ContactInfo.all
  end

  # GET /contact_infos/1
  # GET /contact_infos/1.json
  def show
  end

  # GET /contact_infos/new
  def new
    @contact_info = ContactInfo.new
  end

  # GET /contact_infos/1/edit
  def edit
  end

  # POST /contact_infos
  # POST /contact_infos.json
  def create
    @contact_info = ContactInfo.new(contact_info_params)

    respond_to do |format|
      if @contact_info.save
        format.html { redirect_to @contact_info, notice: 'Contact info was successfully created.' }
        format.json { render :show, status: :created, location: @contact_info }
      else
        format.html { render :new }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_infos/1
  # PATCH/PUT /contact_infos/1.json
  def update
    respond_to do |format|
      if @contact_info.update(contact_info_params)
        format.html { redirect_to @contact_info, notice: 'Contact info was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_info }
      else
        format.html { render :edit }
        format.json { render json: @contact_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_infos/1
  # DELETE /contact_infos/1.json
  def destroy
    @contact_info.destroy
    respond_to do |format|
      format.html { redirect_to contact_infos_url, notice: 'Contact info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_info
      @contact_info = ContactInfo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_info_params
      params.require(:contact_info).permit(:user_id, :type, :name, :value)
    end
end

app/helpers/contact_infos_helper.rb
module ContactInfosHelper
end

app/views/contact_infos/_form.html.erb
<%= form_for(@contact_info) do |f| %>
  <% if @contact_info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_info.errors.count, "error") %> prohibited this contact_info from being saved:</h2>

      <ul>
      <% @contact_info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_area :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_infos/edit.html.erb
<h1>Editing Contact Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_info %> |
<%= link_to 'Back', contact_infos_path %>

app/views/contact_infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contact Infos</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Type</th>
      <th>Name</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_infos.each do |contact_info| %>
      <tr>
        <td><%= contact_info.user_id %></td>
        <td><%= contact_info.type %></td>
        <td><%= contact_info.name %></td>
        <td><%= contact_info.value %></td>
        <td><%= link_to 'Show', contact_info %></td>
        <td><%= link_to 'Edit', edit_contact_info_path(contact_info) %></td>
        <td><%= link_to 'Destroy', contact_info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact info', new_contact_info_path %>

app/views/contact_infos/new.html.erb
<h1>New Contact Info</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_infos_path %>

app/views/contact_infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @contact_info.user_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @contact_info.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @contact_info.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @contact_info.value %>
</p>

<%= link_to 'Edit', edit_contact_info_path(@contact_info) %> |
<%= link_to 'Back', contact_infos_path %>