config/routes.rb
Rails.application.routes.draw do

  get 'less_active_members/:id/resource/:rid/:slug' => 'less_active_members#resource', as: :less_active_member_resource
  
  resources :less_active_members do
    member do
      get 'edit_next'
    end
    collection do
      get 'list'
      post 'import_names'
    end
  end

  resources :personal_history_stories

  resources :personal_history_stories, path: :fifty_two_stories

  resources :text_messages

  resources :notes

  resources :assignments

  resources :tasks

  resources :contact_infos

  get 'welcome/index'

  resources :users

  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]  

  root 'welcome#index'
  
  get 'home/' => 'home#index'

  resources :recipes, only: [:index, :show, :create, :update, :destroy]
end

app/models/personal_history_story.rb
class PersonalHistoryStory < ActiveRecord::Base
end

app/controllers/personal_history_stories_controller.rb
class PersonalHistoryStoriesController < ApplicationController
  before_action :set_personal_history_story, only: [:show, :edit, :update, :destroy]

  # GET /personal_history_stories
  # GET /personal_history_stories.json
  def index
    @personal_history_stories = PersonalHistoryStory.all
  end

  # GET /personal_history_stories/1
  # GET /personal_history_stories/1.json
  def show
  end

  # GET /personal_history_stories/new
  def new
    @personal_history_story = PersonalHistoryStory.new
  end

  # GET /personal_history_stories/1/edit
  def edit
  end

  # POST /personal_history_stories
  # POST /personal_history_stories.json
  def create
    @personal_history_story = PersonalHistoryStory.new(personal_history_story_params)

    respond_to do |format|
      if @personal_history_story.save
        format.html { redirect_to @personal_history_story, notice: 'Personal history story was successfully created.' }
        format.json { render :show, status: :created, location: @personal_history_story }
      else
        format.html { render :new }
        format.json { render json: @personal_history_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_history_stories/1
  # PATCH/PUT /personal_history_stories/1.json
  def update
    respond_to do |format|
      if @personal_history_story.update(personal_history_story_params)
        format.html { redirect_to @personal_history_story, notice: 'Personal history story was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_history_story }
      else
        format.html { render :edit }
        format.json { render json: @personal_history_story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_history_stories/1
  # DELETE /personal_history_stories/1.json
  def destroy
    @personal_history_story.destroy
    respond_to do |format|
      format.html { redirect_to personal_history_stories_url, notice: 'Personal history story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_history_story
      @personal_history_story = PersonalHistoryStory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_history_story_params
      params.require(:personal_history_story).permit(:subject, :body, :took_place_at)
    end
end

app/helpers/personal_history_stories_helper.rb
module PersonalHistoryStoriesHelper
end

app/views/personal_history_stories/_form.html.erb
<%= simple_form_for(@personal_history_story) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject %>
    <%= f.input :body %>
    <%= f.input :took_place_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/personal_history_stories/edit.html.erb
<h1>Editing Personal History Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @personal_history_story %> |
<%= link_to 'Back', personal_history_stories_path %>

app/views/personal_history_stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personal History Stories</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th>Took place at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_history_stories.each do |personal_history_story| %>
      <tr>
        <td><%= personal_history_story.subject %></td>
        <td><%= personal_history_story.body %></td>
        <td><%= personal_history_story.took_place_at %></td>
        <td><%= link_to 'Show', personal_history_story %></td>
        <td><%= link_to 'Edit', edit_personal_history_story_path(personal_history_story) %></td>
        <td><%= link_to 'Destroy', personal_history_story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personal history story', new_personal_history_story_path %>

app/views/personal_history_stories/new.html.erb
<h1>New Personal History Story</h1>

<%= render 'form' %>

<%= link_to 'Back', personal_history_stories_path %>

app/views/personal_history_stories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @personal_history_story.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @personal_history_story.body %>
</p>

<p>
  <strong>Took place at:</strong>
  <%= @personal_history_story.took_place_at %>
</p>

<%= link_to 'Edit', edit_personal_history_story_path(@personal_history_story) %> |
<%= link_to 'Back', personal_history_stories_path %>