config/routes.rb
Rails.application.routes.draw do

  get 'less_active_members/:id/resource/:rid/:slug' => 'less_active_members#resource', as: :less_active_member_resource
  
  resources :less_active_members do
    member do
      get 'edit_next'
    end
    collection do
      get 'list'
      post 'import_names'
    end
  end

  resources :personal_history_stories

  resources :personal_history_stories, path: :fifty_two_stories

  resources :text_messages

  resources :notes

  resources :assignments

  resources :tasks

  resources :contact_infos

  get 'welcome/index'

  resources :users

  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]  

  root 'welcome#index'
  
  get 'home/' => 'home#index'

  resources :recipes, only: [:index, :show, :create, :update, :destroy]
end

app/models/text_message.rb
class TextMessage < ActiveRecord::Base
end

app/controllers/text_messages_controller.rb
class TextMessagesController < ApplicationController
  before_action :set_text_message, only: [:show, :edit, :update, :destroy]

  # GET /text_messages
  # GET /text_messages.json
  def index
    @text_messages = TextMessage.all
  end

  # GET /text_messages/1
  # GET /text_messages/1.json
  def show
  end

  # GET /text_messages/new
  def new
    @text_message = TextMessage.new
  end

  # GET /text_messages/1/edit
  def edit
  end

  # POST /text_messages
  # POST /text_messages.json
  def create
    @text_message = TextMessage.new(text_message_params)

    respond_to do |format|
      if @text_message.save
        format.html { redirect_to @text_message, notice: 'Text message was successfully created.' }
        format.json { render :show, status: :created, location: @text_message }
      else
        format.html { render :new }
        format.json { render json: @text_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /text_messages/1
  # PATCH/PUT /text_messages/1.json
  def update
    respond_to do |format|
      if @text_message.update(text_message_params)
        format.html { redirect_to @text_message, notice: 'Text message was successfully updated.' }
        format.json { render :show, status: :ok, location: @text_message }
      else
        format.html { render :edit }
        format.json { render json: @text_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_messages/1
  # DELETE /text_messages/1.json
  def destroy
    @text_message.destroy
    respond_to do |format|
      format.html { redirect_to text_messages_url, notice: 'Text message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text_message
      @text_message = TextMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_message_params
      params.require(:text_message).permit(:subject, :body, :send_at)
    end
end

app/helpers/text_messages_helper.rb
module TextMessagesHelper
end

app/views/text_messages/_form.html.erb
<%= simple_form_for(@text_message) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject %>
    <%= f.input :send_at %>
    <%= f.input :body, as: :text, :input_html => { :rows => 10 } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/text_messages/edit.html.erb
<h1>Editing Text Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_message %> |
<%= link_to 'Back', text_messages_path %>

app/views/text_messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Text Messages</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th>Send at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @text_messages.each do |text_message| %>
      <tr>
        <td><%= text_message.subject %></td>
        <td><%= text_message.body %></td>
        <td><%= text_message.send_at %></td>
        <td><%= link_to 'Show', text_message %></td>
        <td><%= link_to 'Edit', edit_text_message_path(text_message) %></td>
        <td><%= link_to 'Destroy', text_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Text message', new_text_message_path %>

app/views/text_messages/new.html.erb
<h1>New Text Message</h1>

<%= render 'form' %>

<%= link_to 'Back', text_messages_path %>

app/views/text_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @text_message.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @text_message.body %>
</p>

<p>
  <strong>Send at:</strong>
  <%= @text_message.send_at %>
</p>

<%= link_to 'Edit', edit_text_message_path(@text_message) %> |
<%= link_to 'Back', text_messages_path %>